export const questions = [
  'What makes your character interesting?',
  'What kind of online activities does your character enjoy?',
  'How do you think your character felt after they got tricked?',
  'Have you ever seen a fake message or scam like this before? How did you feel, and what did you do?',
  'If your character had spotted the scam, what could they have done differently?',
  'Why do you think people get tricked by fake messages online?',
  'Why do people fall for phishing scams? What makes them trust a fake email or message?',
  'What things might make someone not see that a message is a scam?',
  'Do you think some people are more at risk than others? Why?',
  'Can you think of any real-life examples of someone falling for a phishing scam? What happened?',
  'Do you think scammers target specific types of people (e.g., older adults, younger people, or people with certain habits)? Why or why not?',
  'If your character had asked for advice before clicking, what could have changed?',
  'How do you feel about people who fall for phishing scams? Is it their fault?',
  'If you were in their place, what would you have done?',
];
