export const questions = [
  'What are the most important warning signs of a phishing scam?',
  'Does your checklist include all the important signs of a phishing scam?',
  'Is your checklist easy to understand? Would your friends and family find it useful?',
  'If you had only 3 seconds to warn someone about a scam, what would you say?',
  'How can your checklist help real people in everyday situations?',
  'What advice would you give your character to stay safe next time?',
  'What are some real-world ways to spread phishing awareness?',
  'What are some ways social media can help people learn about staying safe online, and what are some ways it can make them more vulnerable to scams?',
  'Can you think of a creative way to make learning about phishing fun?',
  'What can make your checklist more memorable or easier for someone to follow?',
  'Do you think a checklist alone is enough to protect people from scams? Or should we teach them other strategies as well?',
  'How can we make the process of spotting phishing scams more fun or engaging for people?',
  'If you could combine your checklist with another tool (e.g., an app or a game), what would it look like?',
  'What do you think is the most common mistake people make when they try to spot phishing scams?',
  'Who do you think needs this checklist the most: adults, teens, or younger kids? Why?',
  'If you could give one tip on how to avoid phishing scams, what would it be?',
  'How can we stay safe from phishing scams even when bad people come up with new ways to trick us?',
  'Should the checklist be designed differently for children, adults, and elderly people? What would be the biggest differences for each group?',
];
